name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install references
        run: sudo apt-get install libgtest-dev -y && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib && sudo apt install build-essential && sudo apt install git && sudo apt-get install -y cppcheck && sudo apt-get install valgrind && sudo apt-get install -y lcov && sudo apt-get install -y gcovr

      - name: build
        run: mkdir build && cd build && cmake .. && make

      - name: tests_under_valgrind
        run: valgrind --leak-check=full --track-origins=yes ./build/tests && valgrind --leak-check=full --track-origins=yes --child-silent-after-fork=yes  ./build/tests_procs

      - name: stress_tests_avg_time
        run: ./build/stress_test && ./build/stress_test_procs

      - name: code coverage
        run: lcov -t "HW_2" -o coverage.txt -c -d . && cp coverage.txt ../

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          flags: unittests
